analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - packages/**
include: package:lints/recommended.yaml

linter:
  rules:
    avoid_print: true
